name: Sync Translated Content

on:
  workflow_dispatch:
    inputs:
      notes:
        description: "Notes"
        required: false
        default: ""
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 1 * * *"

jobs:
  build:
    if: github.repository == 'mdn/translated-content'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        lang:
          - es
          - fr
          - ja
          - ko
          - pt-br
          - ru
          - zh-cn
          - zh-tw

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: mdn/content
          path: mdn/content

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
          cache-dependency-path: mdn/content/yarn.lock

      - name: Install all yarn packages
        working-directory: ${{ github.workspace }}/mdn/content
        run: yarn --frozen-lockfile
        env:
          # https://github.com/microsoft/vscode-ripgrep#github-api-limit-note
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync translated content
        env:
          CONTENT_ROOT: ${{ github.workspace }}/mdn/content/files
          CONTENT_TRANSLATED_ROOT: ${{ github.workspace }}/files
        working-directory: ${{ github.workspace }}/mdn/content
        run: yarn content sync-translated-content ${{ matrix.lang }}

      - name: Create PR with sync for ${{ matrix.lang }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "${{ matrix.lang }}: sync translated content"
          branch: content-sync-${{ matrix.lang }}
          title: "[${{ matrix.lang }}] sync translated content"
          author: mdn-bot <108879845+mdn-bot@users.noreply.github.com>
          body: Yari generated sync
          token: ${{ secrets.AUTOMERGE_TOKEN }}
